repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=79

-   repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8